### ISSUE TITLE
Appsignal.Phoenix.Instrumenter

### ISSUE THREAD

**Issue by scottmessinger** [appsignal/appsignal-docs#100]
According to: http://docs.appsignal.com/elixir/integrations/phoenix.html#phoenix-instrumentation-hooks, `Appsignal.Phoenix.Instrumenter` should exist somewhere in the library. I can't find it. 

Probably related it,  and I get an error here: https://github.com/appsignal/appsignal-elixir/blob/9124eb8b33d07c225007dcca50ca494461df2cfc/lib/appsignal/instrumentation/helpers.ex#L57 because it looks like there isn't a `conn = assign(conn, :app_signal_transaction, ...)`
e.g.
```
** (exit) an exception was raised:
     ** (KeyError) key :appsignal_transaction not found in: %{}
         (appsignal) lib/appsignal/instrumentation/helpers.ex:57: Appsignal.Instrumentation.Helpers.instrument/6
```

On a side note, the number of errors I've found is maddening. I used the library before it hit 1.0 and things went smoothly. Now, it's just breaking left and right. It feels like you haven't actually tried to set up an app by following your documentation. It could just be me, though. I really want to like AppSignal and I'm hoping I've run into all these problems because you've just been so overwhelmed by the positive response to the Elixir integration, you haven't had a time to go back to the docs. If so, congrats! AppSignal seems pretty sweet and I look forward to getting it up and working soon.

**Comment by tombruijn** [comment]
Hi again @scottmessinger ! Thanks for reporting these issues 👍  Sorry to hear your experience hasn't been that great. It's true that our docs are lagging behind a bit. And I'll admit I screwed up some of the examples in the rush to get it live. I'll give it another good review today and fix any issues I find.

About the `Appsignal.Phoenix.Instrumenter` module: It should exist here: https://github.com/appsignal/appsignal-elixir/blob/b38077e6abebc3b05334c700fba32da572c7b48d/lib/appsignal/phoenix/instrumenter.ex
Are you running into an error while trying to use it?

About the `instrumentation` function for Phoenix: Looks like there is still some old code expecting that assignment. We rewrote that pretty recently and I've personally never actually used that instrumentation function using the Phoenix connection. I'll have a look and see what's going wrong there. You can always use the alternative way by [looking up the transaction manually](http://docs.appsignal.com/elixir/instrumentation/instrumentation.html#helper-instrument-helper), but seeing as you reported issue #99 I'm assuming you already tried that 😞 

Do let us know when you run into issues like this. It will help us improve our docs a lot, something we're trying to do a lot more actively right now, but it's a lengthy process

**Comment by scottmessinger** [comment]
Thanks for being so responsive. I've been really impressed by both AppSignal and how it works with Phoenix (back when it was working for me) so I'm excited to see the bugs worked out! Also, docs are hard and time consuming -- I don't envy the task! Good luck and let me know if you want me to test out a branch or anything.

**Comment by tombruijn** [comment]
Hi @scottmessinger,

So far I've reviewed most of the Elixir docs on the documentation website, http://docs.appsignal.com/elixir/. I can't guarantee it's a 100% accurate right now, but we'll continue to update it and also reflect any updates back to the package docs on https://hexdocs.pm/appsignal/

I've created an issue for the broken Phoenix based `instrument` helper function in https://github.com/appsignal/appsignal-elixir/issues/174
We're going to look at why that function (still) exists. It's probably going to be removed, because that's not longer how we keep track of the current transaction.
The alternative for that helper is to use the `instrument` helper function using the `transaction` directly: http://docs.appsignal.com/elixir/instrumentation/instrumentation.html#helper-instrument-helper

Are you still encountering an issue with the `Appsignal.Phoenix.Instrumenter` not being found?

Did you run into any other bugs you've so far not reported?
Do you need any other help getting the AppSignal integration set up? It could be that some of the issues you're still encountering is because we rewrote parts and it no longer behaves the same way.

Let me know what issues you're having so we know what's broken and where :)

Tom

**Comment by jeffkreeftmeijer** [comment]
Hey @scottmessinger,

Thanks a lot for reporting this issue in our documentation, and sorry for the inconvenience. The `instument/1` issue (#174) has been fixed and we've updated the documentation. I'm closing this, please open a new issue when you run into any other errors in the documentation. Thanks again!
