### ISSUE TITLE
Allow users to search the docs website

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#137]
Currently you have to know on which page certain content is or else you need to click through all the pages to find it.

We could offer search to our users.

In the meantime I recommend using this template for your Google search: `site:docs.appsignal.com your search here` to search Google for only our docs website.

**Comment by thijsc** [comment]
Maybe use https://www.algolia.com

**Comment by matsimitsu** [comment]
I hear good things about https://tapirgo.com ;)

**Comment by thijsc** [comment]
But do we have a reliable RSS feed with changes?

**Comment by matsimitsu** [comment]
There's a push API https://tapirgo.com/ (scroll down to API docs).

**Comment by tombruijn** [comment]
Since TapirGo is no longer with us. Do we still want to look for an alternative?

**Comment by jvanbaarsen** [comment]
Wes and I just discussed this and came to the following options:

1. We can go live with the current setup and have the Algolia logo present for the time being.
2. After this we need to run our own crawler as a docker container (https://community.algolia.com/docsearch/run-your-own.html). We can then remove the Algolia logo, and pay them for the search functionality
3. Look for an alternative service where we don't need to run any code ourselves.

**Comment by wesoudshoorn** [comment]
@jvanbaarsen, we still need to pay them even when we host the crawler ourselves?

**Comment by jvanbaarsen** [comment]
@wesoudshoorn Yes, since the searching etc happens via their system.

**Comment by jvanbaarsen** [comment]
@wesoudshoorn I really want to move this along since I got signals from others that they can use this when doing koos as well. it is currently locked on two things I believe:

* There is a bug on mobile
* The Algolia logo.

I want to propose that I take over full ownership of this issue, and fix the responsive issue, and we will ship this *with* the algolia logo, I don't think its that big of a problem. We can then at a later stage remove the logo, but at least we finally offer a search.

**Comment by tombruijn** [comment]
We have something for now. I have some issues with it but at least we have something for now. Let's see how well it works for now.
