### ISSUE TITLE
List run time dependencies of agent

### ISSUE THREAD

**Issue by schnittchen** [appsignal/appsignal-docs#141]
I'm leaving this here because my instrumentation stopped when I packed my app into a small docker image, leaving build-time dependencies out. In my case, the ca-certificates package was missing (obvious, in hind-sight...)

**Comment by schnittchen** [comment]
This dependency was automatically pulled in by the build-time dependencies of the agent, which is why the issue did not apprear previously.

**Comment by tombruijn** [comment]
Hi @schnittchen,

Which Docker container were you using? Most of the ones I tested it on worked with the dependencies listed as requirements on the [installation page in the docs](https://docs.appsignal.com/ruby/installation.html#requirements). 
Let me know which image you are using so that I can see if the package listed on that page are enough.

**Comment by schnittchen** [comment]
Hi Tom, I'm working with elixir:slim right now.

**Comment by tombruijn** [comment]
Ah yes, that one doesn't seem to work. I'll update our docs page.

Thanks for the report!

**Comment by tombruijn** [comment]
I've now gathered all the system dependencies on the [Supported Operating Systems](https://docs.appsignal.com/support/operating-systems.html) page per OS and added the ca-certificates dep.
