### ISSUE TITLE
Node.js v1.0 Docs

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-docs#308]
## Next Steps

- [ ]  The config options for Node.js currently don't render as they need entry into the `data/config_options.yml` file
- [x] Custom metrics documentation should be merged with the existing docs, removing or re-locating any transaction-specific docs
- [x] Mentions of Node.js alongside Elixir and Ruby where needed, etc

**Comment by tombruijn** [comment]
>  The config options for Node.js currently don't render as they need entry into the data/config_options.yml file

:+1:
But I still want to review this solution as I think it's part of the cause for this issue: https://github.com/appsignal/appsignal-docs/issues/269
And the more integrations we get the bigger that YAML file becomes, the more unmaintainable it becomes. Maybe split all the options in separate files so it's more manageable? 🤷‍♂️ 

>  Custom metrics documentation should be merged with the existing docs, removing or re-locating any transaction-specific docs

Yes, since I also rewrote it to include the now removed parts of the https://docs.appsignal.com/metrics/custom-metrics/dashboards.html that were still relevant for how graphs work.

The updated page: https://docs.appsignal.com/metrics/custom.html

---

I think we should leave big rewrites or restructures that aren't required for the 1.0 docs to the "Docs 2.0" project that we shaped.
